# Generated by Django 3.2 on 2022-06-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='livestyle',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='task',
            field=models.CharField(choices=[('slim', 'get slim'), ('save', 'get save'), ('grow', 'get grow')], max_length=10, null=True),
        ),
    ]
