# Generated by Django 3.2 on 2022-06-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220601_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='livestyle',
            field=models.CharField(choices=[('Sedentary', 'Sedentary'), ('Active', 'Active'), ('Sports', 'Sports')], max_length=15, null=True),
        ),
    ]
