# Generated by Django 3.2 on 2022-06-02 18:32

from django.db import migrations, models
import user.validations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='diet',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank='Male', choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.FloatField(error_messages={'required': 'Please enter positive number'}, null=True, validators=[user.validations.validate_positive]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(error_messages={'required': 'Please enter positive number'}, null=True, validators=[user.validations.validate_positive]),
        ),
    ]
