# Generated by Django 3.2 on 2022-06-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20220602_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='growth',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
