# Generated by Django 3.2 on 2022-05-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('focus', models.CharField(max_length=50, verbose_name='focus')),
                ('types', models.CharField(max_length=50, verbose_name='type')),
                ('difficult', models.CharField(max_length=20, verbose_name='difficult')),
                ('equirment', models.CharField(max_length=50, verbose_name='equirement')),
                ('icon', models.CharField(max_length=200, verbose_name='img intro')),
                ('img', models.CharField(max_length=200, verbose_name='img link')),
                ('muscles', models.CharField(max_length=200, verbose_name='img muscles')),
            ],
        ),
    ]
