# Generated by Django 3.2 on 2022-06-02 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('calories', models.PositiveIntegerField(null=True)),
                ('protein', models.FloatField(null=True)),
                ('fats', models.FloatField(null=True)),
                ('carbo', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=100, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('value', models.FloatField(null=True)),
                ('workout', models.PositiveIntegerField(null=True)),
                ('calories', models.ManyToManyField(related_name='d_calories', to='diet.Food')),
                ('carbo', models.ManyToManyField(related_name='d_carbo', to='diet.Food')),
                ('fats', models.ManyToManyField(related_name='d_fats', to='diet.Food')),
                ('name', models.ManyToManyField(related_name='d_name', to='diet.Food')),
                ('protein', models.ManyToManyField(related_name='d_protein', to='diet.Food')),
            ],
        ),
    ]
