# Generated by Django 3.2 on 2022-06-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='volume',
            field=models.CharField(choices=[('gr', 'gr'), ('ml', 'ml')], default='gr', max_length=5),
        ),
    ]
