# Generated by Django 3.2 on 2022-06-04 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_meal_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealyMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.PositiveIntegerField(null=True)),
                ('protein', models.FloatField(null=True)),
                ('fats', models.FloatField(null=True)),
                ('carbo', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=100, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('volume', models.CharField(choices=[('gr', 'gr'), ('ml', 'ml')], default='gr', max_length=5)),
                ('value', models.FloatField(null=True)),
                ('name', models.ManyToManyField(related_name='o_name', to='diet.Food')),
            ],
        ),
    ]
