# Generated by Django 3.2 on 2022-06-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Difficult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True, verbose_name='difficult name')),
            ],
        ),
        migrations.CreateModel(
            name='Equirment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True, verbose_name='equirment name')),
            ],
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True, verbose_name='focus name')),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True, verbose_name='types name')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('icon', models.CharField(max_length=200, null=True, verbose_name='img intro')),
                ('img', models.CharField(max_length=200, null=True, verbose_name='img link')),
                ('muscles', models.CharField(max_length=200, null=True, verbose_name='img muscles')),
                ('difficult', models.ManyToManyField(default='all', to='workout.Difficult')),
                ('equirment', models.ManyToManyField(default='all', to='workout.Equirment')),
                ('focus', models.ManyToManyField(default='all', to='workout.Focus')),
                ('types', models.ManyToManyField(default='all', to='workout.Types')),
            ],
        ),
    ]
