# Generated by Django 4.0.1 on 2022-05-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Difficult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='difficult name')),
            ],
        ),
        migrations.CreateModel(
            name='Equirment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='equirment name')),
            ],
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='focus name')),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='types name')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('icon', models.CharField(max_length=200, verbose_name='img intro')),
                ('img', models.CharField(max_length=200, verbose_name='img link')),
                ('muscles', models.CharField(max_length=200, verbose_name='img muscles')),
                ('difficult', models.ManyToManyField(to='workouts.Difficult')),
                ('equirment', models.ManyToManyField(to='workouts.Equirment')),
                ('focus', models.ManyToManyField(to='workouts.Focus')),
                ('types', models.ManyToManyField(to='workouts.Types')),
            ],
        ),
    ]
