# Generated by Django 4.0.1 on 2022-05-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='difficult',
            field=models.ManyToManyField(default='all', to='workouts.Difficult'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='equirment',
            field=models.ManyToManyField(default='all', to='workouts.Equirment'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='focus',
            field=models.ManyToManyField(default='all', to='workouts.Focus'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='types',
            field=models.ManyToManyField(default='all', to='workouts.Types'),
        ),
    ]
