# Generated by Django 3.2 on 2022-05-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_workout_difficult_alter_workout_equirment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficult', models.CharField(max_length=10)),
                ('distance', models.IntegerField()),
                ('route', models.JSONField()),
            ],
        ),
    ]
