# Generated by Django 3.2 on 2022-06-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastomWalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficult', models.CharField(choices=[('Easy', 'easy'), ('Normal', 'normal'), ('Hard', 'hard')], default='normal', max_length=10)),
                ('country', models.CharField(default='Россия', max_length=20)),
                ('city', models.CharField(default='Москва', max_length=20)),
                ('street', models.CharField(default='Студенческая 33', max_length=50)),
            ],
        ),
    ]
